Dart sass 1.34/version bump
sass-mq/sass-mq pull request #144
Opened 2021-06-01 05:32 UTC by area73

## New bump Version.
* Compatible only with dart-sass 
* Please see CHANGELOG.md to see all the changes

## TODO
I add about 22 jest test to check for functionality, but I left in this MR old test to decide if we should keep them or remove them along with their dependencies to `eyeglass`.
Since they are now all cover with jest test and `sass-true` package and this it will be a good idea to remove them

2021-06-14 10:33 UTC, area73 commented
@kaelig , have you had time to check for this PR?. 
I would really like to have it implemented on your project and get rid of deprecation warnings.
TIA

2021-06-16 02:13 UTC, kaelig commented
Hi, this project isn't a priority for me anymore, would you be open to becoming a core contributor? I can give you admin access to the repo so you can release a beta from this branch and see if that works for you.

I care a lot about good prose and good documentation on this project and I noticed a few typos in this PR. Do you have someone whose first language is English and who could review code comments and documentation changes?

2021-06-16 05:44 UTC, area73 commented
Ok ,great I can become a contributor 👍.

About spelling and typos, I can ask other colleagues to try to do a code review, but they are not native english spoken. But I guess you can always add comments on the PR

2021-06-18 09:34 UTC, ktan88 approved these changes

2021-06-18 17:20 UTC, area73 reviewed
All changes made

2021-06-22 00:06 UTC, kaelig approved these changes
Great start! I finally managed to make time for a review, and have quite a few comments – let me know if you have any questions.

1. Is there a way to still allow folks to write `mq()` instead of having to write `mq.mq()`?

2. Can you create an `example` folder with this structure, showing exactly how it works with this pretty common setup?

```
/example
   /_setup.scss (where Sass MQ is imported and *custom breakpoints* are configured)
   /_layout.scss (example of using mq)
   /_typography.scss (another example of using mq)
   /styles.scss (imports `_header` and `_typography`)
   /styles.css (compiled CSS)
```

Thank you!

2021-06-22 00:06 UTC, kaelig commented on package.json
> +    "sass": "1.35.1",
Should this be prefixed with a `^`?

2021-06-22 00:09 UTC, kaelig commented
>About spelling and typos, I can ask other colleagues to try to do a code review, but they are not native english spoken. But I guess you can always add comments on the PR

Thanks for the fixes! I've added a few comments. Documentation quality and clarity is the top priority for this project, so considering what you mentioned, I'll remain maintainer until someone with awesome technical writing skills and English level steps up.

2021-06-23 09:33 UTC, area73 commented on CHANGELOG.md
> +* Deprecate `$mq-base-font-size` (https://github.com/sass-mq/sass-mq/pull/123)
Yes, my intention was to note that we removed deprecated `$mq-base-font-size`

2021-06-23 10:20 UTC, area73 commented on README.md
>      @import '~sass-mq';
If you are using webpack and want to have mq imported in your JS file, this will work. 
That's how we do it in our react components.

And if you want to use mq from a Sass file then you should do `@use 'path/to/mq'`

2021-06-23 14:23 UTC, area73 commented on .editorconfig
> +indent_size = 2
adding prettier to this library seems to be overwhelming. 

Plus it will add new dependencies to the library making it harder to maintain

2021-06-23 14:26 UTC, area73 commented on .editorconfig
> +indent_size = 2
It looks that I had something wrong on my IDE

2021-06-24 00:04 UTC, area73 commented on test/mq.spec.scss
> +    @include it("should throw a warn and return value converted in em") {
not that easy, because Sass doesn’t (yet) provide a way to catch errors.
There are some workarounds with "sass-true" library, although I don't think is worthless because we will need to bind this testing library to the source code of mq.scss file

Please see:
https://www.oddbird.net/true/docs/api-errors

2021-06-24 00:27 UTC, area73 commented
Ok, so I think that the latest changes that I made will make you happy 😃

* I included a `_mq.import.scss` for backward / legacy compatibility in the way that you can keep using the library as you used to (using `@import 'mq';  ` and exposing everything to global scope 🤮).

* I add several example files as you suggested.

* I add more info on readme doc (🙏 please have a look at my grammar 😳)

2021-07-02 10:22 UTC, anthwinter requested changes

2021-07-02 10:22 UTC, anthwinter commented on README.md
> +functions or mixins and how they are now seen by Sass.
```suggestion
When using the `@use` directive, you have to change your mindset when working with vars,
functions or mixins and how they are now seen by Sass.
```

2021-07-02 10:22 UTC, anthwinter commented on README.md
> +it anywhere as long as the main file had been loaded previously.
```suggestion
Previously, with the `@import` statement any var, function, or mixin were exposed in the global scope.
That means that you could define a var like `$mq-media-type: all` in your main sass file and use
it anywhere as long as the main file had been loaded previously.
```

2021-07-02 10:22 UTC, anthwinter commented on README.md
> +This was possible because vars functions and mixins were set in the global scope.
```suggestion
This was possible because vars, functions, and mixins were set in the global scope.
```

2021-07-02 10:22 UTC, anthwinter commented on README.md
> +One drawback of this behavior was that we need to ensure not to pollute the global scope
```suggestion
One drawback of this behaviour was that we needed to ensure not to pollute the global scope
```

2021-07-02 10:22 UTC, anthwinter commented on README.md
> +collapsing names.
```suggestion
To solve this matter, we mostly used a prefix in vars, functions, or mixins in order to avoid
collapsing names.
```

2021-07-02 10:22 UTC, anthwinter commented on README.md
> +functions or mixins (analog to ES6 import modules).
```suggestion
That means that we explicitly need to include the partial file in each file that may use its vars,
functions or mixins (similar to ES6 import modules).
```

2021-07-02 10:22 UTC, anthwinter commented on README.md
> +So previously we could have a typical setup like this:
```suggestion
So, previously we could have a typical setup like this:
```

2021-07-02 10:22 UTC, anthwinter commented on README.md
> +Now you will need to explicit import `_mq.scss` file in each file that needs to use any var, function
```suggestion
Now, you will need to explicitly import the `_mq.scss` file in each file that needs to use any var, function
```

2021-07-02 10:32 UTC, anthwinter commented
Really awesome work on the PR @area73 - I have added a few suggestions to the docs :)

One thing I am not a fan of is the double naming on the mixin when used with `@use`, e.g. `mq.mq()`.

As this is going to result in a breaking change for v6, would it make sense to update either the file name from `mq` or the mixin itself from `mq` so that it would be used like:

`sass-mq.media()`
`mq.media()`
`mq.rule()`

Or anything else that might suit.

2021-07-02 14:06 UTC, area73 commented
> Really awesome work on the PR @area73 - I have added a few suggestions to the docs :)
> 
> One thing I am not a fan of is the double naming on the mixin when used with `@use`, e.g. `mq.mq()`.
> 
> As this is going to result in a breaking change for v6, would it make sense to update either the file name from `mq` or the mixin itself from `mq` so that it would be used like:
> 
> `sass-mq.media()`
> `mq.media()`
> `mq.rule()`
> 
> Or anything else that might suit.

👋, @anthwinter, all changes made.

About using mq.mq() you don't really need to do such a thing.

You can do either one of these two things, you can keep using `@import`and use `_mq.import.scss`  file (for legacy projects), or you can give a universal name to the imported modules (I think I had some example in one of the comments ,but any way here is another one.

So you can do something like:

```scss 
// main.scss

@use 'path/to/mq.scss' as *

body {
  @include mq(720px) {
     font-size:18px;
  }
}

```

Notice that any imported file with `@use` directive can be given a named scope. 
If you use a universal selector (*) then it is like exposing any var, function, mixin to global scope (but only for that file).

Please have a look at:

https://sass-lang.com/documentation/at-rules/use

PS: Thanks for the code review 👍

2021-07-02 14:14 UTC, area73 commented
So, I guess the next step will be from @kaelig to do a final review and since he is the only maintainer, he is the only one that can do the merge and new version release of the library.

2021-07-02 20:35 UTC, anthwinter approved these changes

2021-07-12 05:45 UTC, area73 commented
@kaelig, this MR has been open for more than 1 month. I think everything is up to date , I added reliable test and examples about the use of it , IMHO is ready for a new version release. Do you have any plans for it?

TIA

2021-07-12 14:12 UTC, kaelig commented
Hey folks, I'm on parental leave for the next 6 weeks. Apologies for the long wait. I'll have a look in September.

As this is a Sass helper with no dependencies, there is no urgency for a fix to be published to npm.

For anyone who lands on this PR was they are looking for a version of Sass MQ compatible with Dart Sass: copy `_mq.scss` from this branch into your project, et _voilà_!

2021-07-13 16:11 UTC, nickstaroba commented
@kaelig If you're still in need of a core contributor, I can help.

2021-07-16 08:52 UTC, pierreburel commented
> Really awesome work on the PR @area73 - I have added a few suggestions to the docs :)
> 
> One thing I am not a fan of is the double naming on the mixin when used with `@use`, e.g. `mq.mq()`.
> 
> As this is going to result in a breaking change for v6, would it make sense to update either the file name from `mq` or the mixin itself from `mq` so that it would be used like:
> 
> `sass-mq.media()`
> `mq.media()`
> `mq.rule()`
> 
> Or anything else that might suit.

I agree with this comment, writing `mq.mq` is weird and using `@use 'mq' as *` kinda break the idea of modules.

It could be easily solved by creating a proxy mixin to `mq`: 

```
@mixin media($params...) {
  @include mq($params...);
}
```

```
@use "mq";

body {
  @include mq.media(720px) {
     font-size:18px;
  }
}
```

And hide it in `_mq.import.scss` : `@forward "mq" hide media […]`.

2021-07-16 10:58 UTC, area73 commented
@pierreburel, your proposal is very similar to what we do in our implementation 👍, but instead of doing the proxy on source (mq), we do it in our implementation.
Something like this:
```scss
// responsive.scss
// stuff related to responsive things, like breakpoints and any other functions that we may find useful
// ....

@mixin mq(
  $from: false,
  $until: false,
  $and: false,
  $media-type: mq.$mq-media-type,
  $breakpoints: $mq-breakpoints,
  $responsive: mq.$mq-responsive,
  $static-breakpoint: mq.$mq-static-breakpoint
) {
  @include mq.mq(
    $from,
    $until,
    $and,
    $media-type,
    $breakpoints,
    $responsive,
    $static-breakpoint
  ) {
    @content;
  }
}
```
This way we keep compatibility and we can opt in to use mq like:

```scss
 @use '/responsive';
 
responsive.mq(...)
 
```
Or going straight with:

```scss
 @use '/responsive' as *;
 
  mq(...)

```

2021-07-19 05:11 UTC, kaelig commented
Thank you @pierreburel, I was literally thinking I should reach out to someone at LunaWeb (or an alumnus) to get feedback on this PR! Such a great coincidence that you'd pop into this thread ❤️ 

Can someone point me to examples showing what other libraries are recommending? I'm still struggling with the ergonomics of the new module system for importing libraries and would love to know if there are any best practices we should follow here.

2021-07-19 12:31 UTC, pierreburel commented
Hey @kaelig 👋 Happy to help: i'm still a user of sass-mq on my Sass projects, and yeah i'm pretty sure Lunaweb is still using too :)

I didn't find a lot of lib which switched to modules, but i did it for one of my own lib: https://github.com/pierreburel/sass-rem

I changed a bit the api to avoid having to write `rem.rem()` by renaming the main function/mixin to `convert` (`rem.convert`), but still exporting `rem` function/mixin for backward compatibility with `@import` or when renaming it with `@use`: https://github.com/pierreburel/sass-rem#but-it-was-shorter-before

One small detail i noticed too: the divide depreciation is just for Dart Sass 2, but it breaks on Dart Sass <1.33 because `math.div` doesn't exist… I fixed that by creating an intermediate function : 

```
// Dart Sass <1.33.0 compatibility
@function _divide($a, $b) {
  @if map.has-key(meta.module-functions("math"), "div") {
    @return math.div($a, $b);
  }

  @return $a / $b;
}
```

2021-07-19 15:51 UTC, area73 commented
Hi @pierreburel 

Actually, there is a function to check if SASS has a function or not (either as a built-in function or a user-defined function).

```scss
meta.function-exists($name) //=> boolean 
function-exists($name) //=> boolean 
```
Returns whether a function named $name is defined, either as a built-in function or a user-defined function.

https://sass-lang.com/documentation/modules/meta#function-exists

But there is a problem with the doc (I will try to make a PR to them to fix their docs), in fact the correct use of that function should be something like:

```scss
meta.function-exists($name, $module: null)  //=> boolean 
function-exists($name, $module: null)  //=> boolean 
```
They miss the module parameter and for you case you could use it as:

```scss
@debug meta.function-exists("div", "math");  // this will print true or false
```

2021-08-09 13:28 UTC, therealpecus commented
@area73 
in order to install the package from the current PR branch one could use
```
npm i -D git://github.com/area73/sass-mq#dart-sass-1.34/version-bump
```
however, I believe you need to add `_mq.import.scss` to the `files` key of the `package.json`.

2021-08-23 19:11 UTC, zzarazza commented
> Hey folks, I'm on parental leave for the next 6 weeks. Apologies for the long wait. I'll have a look in September.
> 
> As this is a rather simple Sass helper with no dependencies, and it can be copied into any project, there is no urgency for a fix to be published to npm.
> 
> For anyone who lands on this PR was they are looking for a version of Sass MQ compatible with Dart Sass: copy `_mq.scss` from this branch into your project, et _voilà_!

I am watching this PR like a hawk because we are using mq extensively in our SASS projects and currently we are suffering the warnings which we can't quiet due to yarn-webpack-whatever and there are too many projects to make this a local file. So really looking forward to this being updated! (not trying to interrupt your parental leave though :) )

2021-08-24 17:50 UTC, kaelig commented
Hi everyone, I've tested locally and made a few changes to the PR - I'll merge this, publish a beta (`yarn add sass-mq@next --dev` should do the trick for most people).

@area73, can you please create a separate PR containing these changes? 🙏🏻 

- Add tests for the `$show-breakpoints` parameter
- Update Sassdoc comments in `_mq.scss` to reflect the latest usage instructions

When these are fixed, we can release a major version!

2021-08-24 17:51 UTC, merged

2021-08-31 08:36 UTC, area73 commented
Hi @kaelig, 
I will open a PR trying to update Sassdoc in _mq.scss.
About the test for  `$show-breakpoints`, there are already two tests for this mixin.
Please have a look at:
https://github.com/sass-mq/sass-mq/blob/8d73d21f2a58d5a6918dc7b9204a1be6d6ebcb65/test/mq.spec.scss#L312

Thanks

2021-08-31 09:29 UTC, area73 commented
... ok now I see what you meant about `$show-breakpoints` param (not the mixin), sorry. I will add also a test for passing default `$show-breakpoints`